name: Build wouac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies (wouac)
        working-directory: ./wouac
        run: npm install

      - name: Build wouac
        working-directory: ./wouac
        run: npm run build

      - name: Install Wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Install WABT (wat2wasm)
        run: |
          sudo apt-get update
          sudo apt-get install -y wabt

      - name: Perform tests
        run: ./run_tests.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wouac-wasm
          path: wouac/dist/wouac.wasm

